### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by mathorin** [Super-Bug-Tracker-Team/super-bug-tracker#4]
Create stylized favicon

**Comment by gamerwoman3d** [comment]
[https://cdn.glitch.global/6103ec87-7cd1-4e3e-92fd-0e50a3625728/favicon.ico?v=1662262895309](url)

This is the favicon.ico that I threw together.  It's embedded in the changes I pushed to the backfill-issues branch.  We can merge those changes if someone can review them and ensure that I didn't mess up the .env file.
