### ISSUE TITLE
Multiple users on project hosted to MongoDB

### ISSUE THREAD

**Issue by JonnyDino** [Super-Bug-Tracker-Team/super-bug-tracker#6]
Setting up a MongoDB database to work with multiple users on one project.

https://docs.google.com/document/d/1j2Vc_BgQpMHdVJR-DcbYCyjcNpWb-Hf_Yb87Hy8Ysws/edit?usp=sharing

**Comment by mathorin** [comment]
Initial setup completed. Invites sent to those that provided email addresses so far.

**Comment by mathorin** [comment]
@intelagense has his setup working. Issue can be closed once another user has successfully connected and added a 'bug'

**Comment by intelagense** [comment]
Closing the issue. We have multiple users now :+1:
